snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: "%env(REDIS_URL)%"
      logging: true
      options:
        connection_timeout: 10
    cache:
      type: predis
      alias: cache
      dsn: "%env(REDIS_URL)%/1"
      logging: true
      options:
        profile: 2.2
        connection_timeout: 10
        read_write_timeout: 30
    session:
      type: predis
      alias: session
      dsn: "%env(REDIS_URL)%/2"
      logging: true
      options:
        connection_timeout: 10
  session:
    client: session
    prefix: sess

  doctrine:
    metadata_cache:
      client: cache
      entity_manager: default          # the name of your entity_manager connection
      document_manager: default        # the name of your document_manager connection
    result_cache:
      client: cache
      entity_manager: [default]        # you may specify multiple entity_managers
    query_cache:
      client: cache
      entity_manager: default
    second_level_cache:
      client: cache
      entity_manager: default
